// Top Indian and international airports used in SkyVayu
export const AIRPORTS = [
  { iata: 'BOM', name: 'Chhatrapati Shivaji Maharaj International Airport', city: 'Mumbai' },
  { iata: 'DEL', name: 'Indira Gandhi International Airport', city: 'Delhi' },
  { iata: 'BLR', name: 'Kempegowda International Airport', city: 'Bengaluru' },
  { iata: 'MAA', name: 'Chennai International Airport', city: 'Chennai' },
  { iata: 'HYD', name: 'Rajiv Gandhi International Airport', city: 'Hyderabad' },
  { iata: 'CCU', name: 'Netaji Subhas Chandra Bose International Airport', city: 'Kolkata' },
  { iata: 'GOI', name: 'Goa International Airport', city: 'Goa' },
  { iata: 'AMD', name: 'Sardar Vallabhbhai Patel International Airport', city: 'Ahmedabad' },
  { iata: 'PNQ', name: 'Pune Airport', city: 'Pune' },
  { iata: 'JAI', name: 'Jaipur International Airport', city: 'Jaipur' },
  { iata: 'LKO', name: 'Chaudhary Charan Singh International Airport', city: 'Lucknow' },
  { iata: 'IXC', name: 'Chandigarh Airport', city: 'Chandigarh' },
  { iata: 'PAT', name: 'Jay Prakash Narayan Airport', city: 'Patna' },
  { iata: 'BBI', name: 'Biju Patnaik International Airport', city: 'Bhubaneswar' },
  { iata: 'GAU', name: 'Lokpriya Gopinath Bordoloi International Airport', city: 'Guwahati' },
  { iata: 'IXB', name: 'Bagdogra Airport', city: 'Siliguri' },
  { iata: 'VNS', name: 'Lal Bahadur Shastri International Airport', city: 'Varanasi' },
  { iata: 'IDR', name: 'Devi Ahilyabai Holkar Airport', city: 'Indore' },
  { iata: 'NAG', name: 'Dr. Babasaheb Ambedkar International Airport', city: 'Nagpur' },
  { iata: 'COK', name: 'Cochin International Airport', city: 'Kochi' },
  { iata: 'TRV', name: 'Trivandrum International Airport', city: 'Thiruvananthapuram' },
  { iata: 'IXM', name: 'Madurai Airport', city: 'Madurai' },
  { iata: 'IXL', name: 'Kushok Bakula Rimpochee Airport', city: 'Leh' },
  { iata: 'SXR', name: 'Sheikh ul-Alam Airport', city: 'Srinagar' },
  { iata: 'ATQ', name: 'Sri Guru Ram Dass Jee International Airport', city: 'Amritsar' },
  { iata: 'DED', name: 'Jolly Grant Airport', city: 'Dehradun' },
  { iata: 'VGA', name: 'Vijayawada Airport', city: 'Vijayawada' },
  { iata: 'IXR', name: 'Birsa Munda Airport', city: 'Ranchi' },
  { iata: 'RPR', name: 'Swami Vivekananda Airport', city: 'Raipur' },
  { iata: 'UDR', name: 'Maharana Pratap Airport', city: 'Udaipur' },
  { iata: 'JDH', name: 'Jodhpur Airport', city: 'Jodhpur' },
  { iata: 'JSA', name: 'Jaisalmer Airport', city: 'Jaisalmer' },
  { iata: 'DIB', name: 'Dibrugarh Airport', city: 'Dibrugarh' },
  { iata: 'IMF', name: 'Imphal Airport', city: 'Imphal' },
  { iata: 'IXZ', name: 'Veer Savarkar International Airport', city: 'Port Blair' },
  // International
  { iata: 'DXB', name: 'Dubai International Airport', city: 'Dubai' },
  { iata: 'AUH', name: 'Abu Dhabi International Airport', city: 'Abu Dhabi' },
  { iata: 'SIN', name: 'Singapore Changi Airport', city: 'Singapore' },
  { iata: 'BKK', name: 'Suvarnabhumi Airport', city: 'Bangkok' },
  { iata: 'KUL', name: 'Kuala Lumpur International Airport', city: 'Kuala Lumpur' },
  { iata: 'LHR', name: 'Heathrow Airport', city: 'London' },
  { iata: 'CDG', name: 'Charles de Gaulle Airport', city: 'Paris' },
  { iata: 'JFK', name: 'John F. Kennedy International Airport', city: 'New York' },
  { iata: 'NRT', name: 'Narita International Airport', city: 'Tokyo' },
  { iata: 'HKG', name: 'Hong Kong International Airport', city: 'Hong Kong' },
  { iata: 'KTM', name: 'Tribhuvan International Airport', city: 'Kathmandu' },
  { iata: 'CMB', name: 'Bandaranaike International Airport', city: 'Colombo' },
  { iata: 'DAC', name: 'Hazrat Shahjalal International Airport', city: 'Dhaka' },
  { iata: 'MLE', name: 'Velana International Airport', city: 'Malé' },
]
